hello:
  replicaCount: 1
  image:
    repository: registry.baloise.dev/example/gitops-nginx-demo
    tag: b28c3906c883550a8ce552062f645331d1451b93
  network:
    http:
      servicePort: 8080
      ingress:
        host: kup-hello.apps.okd.baloise.dev
